"""Default platform feature flags."""

ENABLE_PAPER_TRADING = True
ENABLE_LIVE_TRADING = False
ENABLE_OPTIONS_ENGINE = True
ENABLE_CRYPTO_SCANNER = True
ENABLE_STOCK_SCANNER = True
ENABLE_AI_LAB = True
ENABLE_DEEP_DIVE_DRAWER = True
ENABLE_MOCK_DATA = False
