export const STOCK_DEEP_DIVE_SOURCE_LABEL = "Manual thesis imported from legacy v8 HTML";

export const STOCK_DEEP_DIVE_CONFIRMATION = {
  CONFIRMED: "Confirmed by YucaTana",
  PARTIAL: "Partially Confirmed",
  NOT_CONFIRMED: "Not Confirmed",
  CONFLICTING: "Conflicting",
  DATA_INSUFFICIENT: "Data Insufficient",
};

export const STOCK_DEEP_DIVE_RATINGS = {
  STRONG_CANDIDATE: "STRONG CANDIDATE",
  CANDIDATE: "CANDIDATE",
  WATCH: "WATCH",
  AVOID: "AVOID",
  SHORT_WATCH: "SHORT WATCH",
};

const LEGACY_THESES = [
  {
    symbol: "OXY",
    exchange: "NYSE",
    name: "Occidental Petroleum",
    sector: "Energy",
    theme: "Energy",
    thesisStatus: "manual",
    rating: STOCK_DEEP_DIVE_RATINGS.WATCH,
    manualConfidence: null,
    uploadedLabel: "Legacy Top Pick",
    manualThesisHeadline: "Oil beta with capital-return and balance-sheet optionality.",
    manualThesisText: "Manual thesis view: OXY can screen well when crude stabilizes, energy breadth improves, and debt reduction or shareholder-return headlines support the equity. This is not a live recommendation until current quote, volume, macro, and Market Brain inputs confirm it.",
    catalysts: [
      { tone: "bull", text: "Energy tape strength and crude price resilience would support the thesis." },
      { tone: "neutral", text: "Balance-sheet improvement and capital-return language need current source validation." },
      { tone: "bear", text: "Commodity reversal or risk-off equity tape can quickly weaken the setup." },
    ],
    analystNotes: ["Manual analyst context only; live analyst estimates are unavailable until a connected research provider supplies them."],
    keyRisks: ["Crude volatility", "Debt sensitivity", "Sector rotation out of energy", "Manual catalyst text needs refresh"],
    manualTarget: null,
    manualStop: null,
    playType: "Energy beta watch",
    riskReward: "Requires live support/resistance and volatility data before any risk framework is trusted.",
    sourceLabel: STOCK_DEEP_DIVE_SOURCE_LABEL,
    lastReviewedAt: "2026-05-30T00:00:00.000Z",
  },
  {
    symbol: "NVDA",
    exchange: "NASDAQ",
    name: "NVIDIA Corporation",
    sector: "AI",
    theme: "AI Infrastructure",
    thesisStatus: "manual",
    rating: STOCK_DEEP_DIVE_RATINGS.WATCH,
    manualConfidence: null,
    uploadedLabel: "Legacy Top Pick",
    manualThesisHeadline: "AI infrastructure leader, but price action must confirm the setup.",
    manualThesisText: "Manual thesis view: NVDA remains a flagship AI infrastructure name. YucaTana should require live trend, momentum, volume, and data-quality confirmation before upgrading this from a watchlist thesis to a candidate.",
    catalysts: [
      { tone: "bull", text: "AI accelerator demand and data-center capex can support the long-term narrative." },
      { tone: "neutral", text: "Earnings, margin, and supply-chain details require current cited research." },
      { tone: "bear", text: "Crowded positioning, valuation sensitivity, or export restrictions can pressure the setup." },
    ],
    analystNotes: ["Manual thesis only; no current analyst rating is implied."],
    keyRisks: ["Crowding", "Valuation compression", "Export controls", "Earnings volatility"],
    manualTarget: null,
    manualStop: null,
    playType: "AI momentum / trend watch",
    riskReward: "Needs live invalidation level, volatility, and relative strength before ranking.",
    sourceLabel: STOCK_DEEP_DIVE_SOURCE_LABEL,
    lastReviewedAt: "2026-05-30T00:00:00.000Z",
  },
  {
    symbol: "META",
    exchange: "NASDAQ",
    name: "Meta Platforms",
    sector: "Tech",
    theme: "AI Ads / Platforms",
    thesisStatus: "manual",
    rating: STOCK_DEEP_DIVE_RATINGS.WATCH,
    manualConfidence: null,
    uploadedLabel: "Legacy Top Pick",
    manualThesisHeadline: "Ad platform scale plus AI tooling, subject to live confirmation.",
    manualThesisText: "Manual thesis view: META can benefit when ad demand, AI engagement tools, and expense discipline line up. The card must be validated by current price action, source health, and catalyst freshness before it is treated as a current opportunity.",
    catalysts: [
      { tone: "bull", text: "AI-enhanced advertising products and engagement tools can improve monetization." },
      { tone: "neutral", text: "Expense discipline and capex trajectory need current earnings context." },
      { tone: "bear", text: "Regulatory pressure or ad-cycle weakness can offset platform strength." },
    ],
    analystNotes: ["Manual analyst context only; estimates unavailable until a live provider supplies them."],
    keyRisks: ["Regulation", "Ad cycle weakness", "AI capex scrutiny", "Manual catalyst staleness"],
    manualTarget: null,
    manualStop: null,
    playType: "Platform quality watch",
    riskReward: "Requires current quote and relative strength before ranking.",
    sourceLabel: STOCK_DEEP_DIVE_SOURCE_LABEL,
    lastReviewedAt: "2026-05-30T00:00:00.000Z",
  },
  {
    symbol: "TSLA",
    exchange: "NASDAQ",
    name: "Tesla Inc.",
    sector: "Auto",
    theme: "EV / Autonomy",
    thesisStatus: "manual",
    rating: STOCK_DEEP_DIVE_RATINGS.WATCH,
    manualConfidence: null,
    uploadedLabel: "Legacy Top Pick",
    manualThesisHeadline: "High-beta EV/autonomy narrative requires strict confirmation.",
    manualThesisText: "Manual thesis view: TSLA can move sharply when autonomy, delivery, margin, or product-cycle narratives improve. Because volatility is structurally high, YucaTana should demand cleaner live trend and risk/reward inputs before elevating it.",
    catalysts: [
      { tone: "bull", text: "Autonomy, robotics, or product-cycle headlines can accelerate momentum." },
      { tone: "neutral", text: "Delivery and margin context must be sourced from current data." },
      { tone: "bear", text: "Price cuts, margin pressure, and high-beta drawdowns can invalidate the thesis." },
    ],
    analystNotes: ["Manual thesis only; no live target or rating supplied."],
    keyRisks: ["High volatility", "Margin pressure", "Execution risk", "Narrative reversals"],
    manualTarget: null,
    manualStop: null,
    playType: "High-beta momentum watch",
    riskReward: "Needs live volatility and invalidation data before action framework.",
    sourceLabel: STOCK_DEEP_DIVE_SOURCE_LABEL,
    lastReviewedAt: "2026-05-30T00:00:00.000Z",
  },
  {
    symbol: "XLE",
    exchange: "AMEX",
    name: "Energy Select Sector SPDR Fund",
    sector: "ETF",
    theme: "Energy Sector",
    thesisStatus: "manual",
    rating: STOCK_DEEP_DIVE_RATINGS.WATCH,
    manualConfidence: null,
    uploadedLabel: "Legacy Top Pick",
    manualThesisHeadline: "Sector-level energy exposure for cleaner theme confirmation.",
    manualThesisText: "Manual thesis view: XLE can act as the cleaner sector expression when individual energy names carry company-specific risk. Current breadth, crude tape, and ETF momentum must confirm the thesis.",
    catalysts: [
      { tone: "bull", text: "Energy sector breadth and crude strength can support XLE." },
      { tone: "neutral", text: "ETF flow and sector rotation need live confirmation." },
      { tone: "bear", text: "Falling crude or broad risk-off conditions can weaken the sector trade." },
    ],
    analystNotes: ["Manual sector thesis; not a live ETF recommendation."],
    keyRisks: ["Commodity reversal", "Sector rotation", "Broad market selloff"],
    manualTarget: null,
    manualStop: null,
    playType: "Sector ETF watch",
    riskReward: "Needs live trend and support/resistance data.",
    sourceLabel: STOCK_DEEP_DIVE_SOURCE_LABEL,
    lastReviewedAt: "2026-05-30T00:00:00.000Z",
  },
  {
    symbol: "CVX",
    exchange: "NYSE",
    name: "Chevron Corporation",
    sector: "Energy",
    theme: "Integrated Energy",
    thesisStatus: "manual",
    rating: STOCK_DEEP_DIVE_RATINGS.WATCH,
    manualConfidence: null,
    uploadedLabel: "Legacy Top Pick",
    manualThesisHeadline: "Integrated energy quality with dividend and commodity sensitivity.",
    manualThesisText: "Manual thesis view: CVX can fit a steadier energy-quality profile when crude, dividends, and integrated margins support the tape. It still requires live confirmation from price, volume, and sector breadth.",
    catalysts: [
      { tone: "bull", text: "Integrated energy cash-flow resilience can support relative strength." },
      { tone: "neutral", text: "Dividend and buyback context should be refreshed from current filings or reports." },
      { tone: "bear", text: "Commodity weakness and project execution risk can weigh on the setup." },
    ],
    analystNotes: ["Manual thesis only; live estimates unavailable."],
    keyRisks: ["Oil and gas price risk", "Project execution", "Sector drawdown"],
    manualTarget: null,
    manualStop: null,
    playType: "Energy quality watch",
    riskReward: "Requires live support/resistance and volatility data.",
    sourceLabel: STOCK_DEEP_DIVE_SOURCE_LABEL,
    lastReviewedAt: "2026-05-30T00:00:00.000Z",
  },
  {
    symbol: "AAPL",
    exchange: "NASDAQ",
    name: "Apple Inc.",
    sector: "Tech",
    theme: "Consumer Tech / Services",
    thesisStatus: "manual",
    rating: STOCK_DEEP_DIVE_RATINGS.WATCH,
    manualConfidence: null,
    uploadedLabel: "Legacy Top Pick",
    manualThesisHeadline: "Quality compounder thesis depends on services, devices, and relative strength.",
    manualThesisText: "Manual thesis view: AAPL can screen as a quality technology anchor when services growth, product cycles, and shareholder returns support sentiment. Live trend and catalyst freshness decide whether it is actionable.",
    catalysts: [
      { tone: "bull", text: "Services mix and installed-base monetization can support the thesis." },
      { tone: "neutral", text: "Product-cycle and AI-device narratives need current cited research." },
      { tone: "bear", text: "Hardware cycle weakness or regulatory pressure can cap upside." },
    ],
    analystNotes: ["Manual thesis only; no live analyst rating implied."],
    keyRisks: ["Hardware demand", "Regulatory pressure", "China exposure", "Valuation sensitivity"],
    manualTarget: null,
    manualStop: null,
    playType: "Quality tech watch",
    riskReward: "Needs current price action and relative strength confirmation.",
    sourceLabel: STOCK_DEEP_DIVE_SOURCE_LABEL,
    lastReviewedAt: "2026-05-30T00:00:00.000Z",
  },
  {
    symbol: "MSFT",
    exchange: "NASDAQ",
    name: "Microsoft Corporation",
    sector: "Tech",
    theme: "Cloud / AI Platform",
    thesisStatus: "manual",
    rating: STOCK_DEEP_DIVE_RATINGS.WATCH,
    manualConfidence: null,
    uploadedLabel: "Legacy Top Pick",
    manualThesisHeadline: "Cloud and AI platform durability with valuation discipline required.",
    manualThesisText: "Manual thesis view: MSFT can remain a core AI/cloud platform thesis when Azure, enterprise software, and AI monetization stay aligned. YucaTana needs live momentum, volume, and data-quality checks before ranking it highly.",
    catalysts: [
      { tone: "bull", text: "Azure growth and AI platform adoption can support leadership." },
      { tone: "neutral", text: "Capex, margins, and enterprise demand need current earnings context." },
      { tone: "bear", text: "Valuation compression or slower cloud growth can weaken the thesis." },
    ],
    analystNotes: ["Manual thesis only; current analyst estimates unavailable."],
    keyRisks: ["Cloud deceleration", "AI capex scrutiny", "Valuation risk"],
    manualTarget: null,
    manualStop: null,
    playType: "Cloud AI quality watch",
    riskReward: "Requires live quote, trend, and invalidation data.",
    sourceLabel: STOCK_DEEP_DIVE_SOURCE_LABEL,
    lastReviewedAt: "2026-05-30T00:00:00.000Z",
  },
];

export function getLegacyStockTheses() {
  return LEGACY_THESES.map((item) => ({
    ...item,
    catalysts: item.catalysts.map((catalyst) => ({ ...catalyst })),
    analystNotes: [...item.analystNotes],
    keyRisks: [...item.keyRisks],
  }));
}

export function normalizeStockThesis(input = {}) {
  const symbol = String(input.symbol || input.ticker || "").trim().toUpperCase();
  return {
    symbol,
    exchange: input.exchange || "NYSE",
    name: input.name || symbol,
    sector: input.sector || "Equity",
    theme: input.theme || input.sector || "Equity",
    thesisStatus: input.thesisStatus || "manual",
    rating: input.rating || STOCK_DEEP_DIVE_RATINGS.WATCH,
    manualConfidence: Number.isFinite(Number(input.manualConfidence)) ? Number(input.manualConfidence) : null,
    uploadedLabel: input.uploadedLabel || "Manual Thesis Label",
    manualThesisHeadline: input.manualThesisHeadline || "Manual thesis requires live validation.",
    manualThesisText: input.manualThesisText || "Manual thesis imported from legacy HTML. Needs validation against current YucaTana market data.",
    catalysts: Array.isArray(input.catalysts) ? input.catalysts : [],
    analystNotes: Array.isArray(input.analystNotes) ? input.analystNotes : [],
    keyRisks: Array.isArray(input.keyRisks) ? input.keyRisks : [],
    manualTarget: Number.isFinite(Number(input.manualTarget)) ? Number(input.manualTarget) : null,
    manualStop: Number.isFinite(Number(input.manualStop)) ? Number(input.manualStop) : null,
    playType: input.playType || "Manual thesis watch",
    riskReward: input.riskReward || "Risk/reward unavailable until live data validates it.",
    sourceLabel: input.sourceLabel || STOCK_DEEP_DIVE_SOURCE_LABEL,
    lastReviewedAt: input.lastReviewedAt || new Date().toISOString(),
  };
}
